In [1]:
import pandas as pd

In [2]:
# Cargar el archivo CSV
datos = pd.read_csv("DatosA&B11-Proy3.csv")

In [3]:
# Lista de columnas a eliminar
columnas_eliminar = ["estu_consecutivo", "cole_cod_dane_establecimiento", "cole_cod_dane_sede", 
                     "cole_cod_depto_ubicacion", "cole_cod_mcpio_ubicacion", "cole_codigo_icfes", 
                     "cole_nombre_establecimiento", "cole_nombre_sede","cole_sede_principal", "estu_cod_depto_presentacion",
                     "estu_cod_mcpio_presentacion", "estu_cod_reside_depto", "estu_cod_reside_mcpio", "cole_depto_ubicacion", "estu_depto_reside",
                     "estu_estudiante","estu_estadoinvestigacion", "estu_mcpio_reside", "estu_fechanacimiento", "estu_genero", "fami_cuartoshogar", 
                     "fami_educacionmadre", "estu_pais_reside", "fami_educacionpadre", "fami_personashogar", "cole_mcpio_ubicacion", "estu_mcpio_presentacion", "cole_jornada", 'cole_naturaleza']

# Eliminar las columnas
datos_limpios = datos.drop(columnas_eliminar, axis=1)

In [4]:
# Seleccionar solo las columnas de interés
columnas_interes = ["desemp_ingles", "punt_ingles", "punt_matematicas", 
                    "punt_sociales_ciudadanas", "punt_c_naturales", 
                    "punt_lectura_critica", "punt_global"]

# Eliminar filas con valores nulos en las columnas de interés
datos_limpios = datos_limpios.dropna(subset=columnas_interes, how='any')

# Verificar la cantidad de registros después de eliminar las filas con valores nulos
print(len(datos_limpios))

635406

In [5]:
# Verificar si hay valores nulos en todo el dataframe limpio
print(datos_limpios.isnull().sum())

periodo                          0
estu_tipodocumento               0
cole_area_ubicacion              0
cole_bilingue               109467
cole_calendario                  0
cole_caracter                23987
cole_genero                      0
estu_depto_presentacion          0
estu_nacionalidad                0
estu_privado_libertad            0
fami_estratovivienda         33134
fami_tieneautomovil          21573
fami_tienecomputador         20203
fami_tieneinternet           30940
fami_tienelavadora           20129
desemp_ingles                    0
punt_ingles                      0
punt_matematicas                 0
punt_sociales_ciudadanas         0
punt_c_naturales                 0
punt_lectura_critica             0
punt_global                      0
dtype: int64

In [6]:
# Eliminar filas con valores nulos en todo el dataframe limpio
datos_limpios = datos_limpios.dropna()

# Verificar la cantidad de registros después de eliminar filas con valores nulos
print(len(datos_limpios))

487887

In [7]:
datos_limpios

,periodo,estu_tipodocumento,cole_area_ubicacion,cole_bilingue,cole_calendario,cole_caracter,cole_genero,estu_depto_presentacion,estu_nacionalidad,estu_privado_libertad,...,fami_tienecomputador,fami_tieneinternet,fami_tienelavadora,desemp_ingles,punt_ingles,punt_matematicas,punt_sociales_ciudadanas,punt_c_naturales,punt_lectura_critica,punt_global
0,20224,TI,URBANO,N,A,TÉCNICO,MIXTO,ANTIOQUIA,COLOMBIA,N,...,Si,Si,Si,A-,35.0,48.0,46,38,49,222
1,20224,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,ANTIOQUIA,COLOMBIA,N,...,Si,Si,No,A-,40.0,43.0,28,44,44,199
2,20224,TI,URBANO,N,A,ACADÉMICO,FEMENINO,ANTIOQUIA,COLOMBIA,N,...,Si,Si,Si,A2,58.0,48.0,59,47,58,267
4,20224,TI,URBANO,N,A,ACADÉMICO,MIXTO,ANTIOQUIA,COLOMBIA,N,...,Si,Si,Si,B1,76.0,67.0,75,55,75,343
6,20224,TI,URBANO,N,A,ACADÉMICO,MIXTO,BOGOTÁ,COLOMBIA,N,...,Si,Si,Si,A2,61.0,57.0,58,58,60,292
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
635563,20224,TI,URBANO,N,A,ACADÉMICO,MIXTO,BOGOTÁ,COLOMBIA,N,...,Si,Si,Si,A1,57.0,62.0,59,58,62,300
635564,20224,CC,URBANO,N,A,ACADÉMICO,MIXTO,ANTIOQUIA,COLOMBIA,N,...,No,Si,Si,A1,52.0,44.0,29,41,39,197
635565,20224,TI,URBANO,N,A,ACADÉMICO,MIXTO,BOGOTÁ,COLOMBIA,N,...,Si,Si,Si,A-,40.0,51.0,31,39,37,198
635566,20224,TI,URBANO,N,A,TÉCNICO,MIXTO,ANTIOQUIA,COLOMBIA,N,...,No,Si,Si,A-,36.0,45.0,30,37,44,194
635567,20224,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,ANTIOQUIA,COLOMBIA,N,...,No,Si,No,A2,67.0,77.0,73,66,50,333

In [14]:
# Verificar los valores únicos
#print(datos_limpios['estu_tipodocumento'].value_counts())
#print(datos_limpios['cole_calendario'].value_counts())
#print(datos_limpios['cole_caracter'].value_counts())
#print(datos_limpios['fami_estratovivienda'].value_counts())
#print(datos_limpios['cole_bilingue'].value_counts())
#print(datos_limpios['estu_privado_libertad'].value_counts())
#print(datos_limpios['estu_nacionalidad'].value_counts())
#print(datos_limpios['desemp_ingles'].value_counts())

desemp_ingles
A-    179925
A1    134526
A2     91937
B1     57744
B+     23755
Name: count, dtype: int64

In [11]:
# Tipos de documento que queremos mantener
tipos_documento_validos = ['TI', 'CC', 'CE', 'PEP']

# Filtrar el dataframe para mantener solo los registros con los tipos de documento válidos y cole_calendario diferente de 'OTRO'
datos_filtrados = datos_limpios[(datos_limpios['estu_tipodocumento'].isin(tipos_documento_validos)) & 
                                (datos_limpios['cole_calendario'] != 'OTRO') &
                                (datos_limpios['fami_estratovivienda'] != "Sin Estrato") &
                                (datos_limpios['estu_nacionalidad'] == "COLOMBIA")]

# Verificar la cantidad de registros después del filtrado
print(len(datos_filtrados))

472323

In [12]:
# Lista de columnas a modificar
columns_to_convert = ['fami_tieneautomovil', 'fami_tienecomputador', 'fami_tieneinternet', 'fami_tienelavadora']

datos_filtrados[columns_to_convert] = datos_filtrados[columns_to_convert].replace({'Si': 1, 'No': 0})

# Quitar la palabra 'Estrato' de la columna 'estrato'
datos_filtrados['fami_estratovivienda'] = datos_filtrados['fami_estratovivienda'].str.replace('Estrato ', '')

#Cambiar a numeros
datos_filtrados['estu_tipodocumento'] = datos_filtrados['estu_tipodocumento'].replace({'CC': 0, 'TI': 1,'CE': 2,'PEP': 3})
datos_filtrados['cole_area_ubicacion'] = datos_filtrados['cole_area_ubicacion'].replace({'URBANO': 0, 'RURAL': 1})
datos_filtrados['cole_bilingue'] = datos_filtrados['cole_bilingue'].replace({'N': 0, 'S': 1})
datos_filtrados['cole_calendario'] = datos_filtrados['cole_calendario'].replace({'A': 0, 'B': 1})
datos_filtrados['cole_genero'] = datos_filtrados['cole_genero'].replace({'MIXTO': 0, 'FEMENINO': 1, 'MASCULINO': 2})
datos_filtrados['cole_caracter'] = datos_filtrados['cole_caracter'].replace({'TÉCNICO': 0, 'TÉCNICO/ACADÉMICO': 1, 'ACADÉMICO': 2})
datos_filtrados['estu_depto_presentacion'] = datos_filtrados['estu_depto_presentacion'].replace({'ANTIOQUIA': 0, 'BOGOTÁ': 1})

C:\Users\valen\AppData\Local\Temp\ipykernel_121484\4216117425.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  datos_filtrados[columns_to_convert] = datos_filtrados[columns_to_convert].replace({'Si': 1, 'No': 0})
C:\Users\valen\AppData\Local\Temp\ipykernel_121484\4216117425.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datos_filtrados[columns_to_convert] = datos_filtrados[columns_to_convert].replace({'Si': 1, 'No': 0})
C:\Users\valen\AppData\Local\Temp\ipykernel_121484\4216117425.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datos_filtrados['fami_estratovivienda'] = datos_filtrados['fami_estratovivienda'].str.replace('Estrato ', '')
C:\Users\valen\AppData\Local\Temp\ipykernel_121484\4216117425.py:10: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  datos_filtrados['estu_tipodocumento'] = datos_filtrados['estu_tipodocumento'].replace({'CC': 0, 'TI': 1,'CE': 2,'PEP': 3})
C:\Users\valen\AppData\Local\Temp\ipykernel_121484\4216117425.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datos_filtrados['estu_tipodocumento'] = datos_filtrados['estu_tipodocumento'].replace({'CC': 0, 'TI': 1,'CE': 2,'PEP': 3})
C:\Users\valen\AppData\Local\Temp\ipykernel_121484\4216117425.py:11: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  datos_filtrados['cole_area_ubicacion'] = datos_filtrados['cole_area_ubicacion'].replace({'URBANO': 0, 'RURAL': 1})
C:\Users\valen\AppData\Local\Temp\ipykernel_121484\4216117425.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datos_filtrados['cole_area_ubicacion'] = datos_filtrados['cole_area_ubicacion'].replace({'URBANO': 0, 'RURAL': 1})
C:\Users\valen\AppData\Local\Temp\ipykernel_121484\4216117425.py:12: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  datos_filtrados['cole_bilingue'] = datos_filtrados['cole_bilingue'].replace({'N': 0, 'S': 1})
C:\Users\valen\AppData\Local\Temp\ipykernel_121484\4216117425.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datos_filtrados['cole_bilingue'] = datos_filtrados['cole_bilingue'].replace({'N': 0, 'S': 1})
C:\Users\valen\AppData\Local\Temp\ipykernel_121484\4216117425.py:13: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  datos_filtrados['cole_calendario'] = datos_filtrados['cole_calendario'].replace({'A': 0, 'B': 1})
C:\Users\valen\AppData\Local\Temp\ipykernel_121484\4216117425.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datos_filtrados['cole_calendario'] = datos_filtrados['cole_calendario'].replace({'A': 0, 'B': 1})
C:\Users\valen\AppData\Local\Temp\ipykernel_121484\4216117425.py:14: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  datos_filtrados['cole_genero'] = datos_filtrados['cole_genero'].replace({'MIXTO': 0, 'FEMENINO': 1, 'MASCULINO': 2})
C:\Users\valen\AppData\Local\Temp\ipykernel_121484\4216117425.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datos_filtrados['cole_genero'] = datos_filtrados['cole_genero'].replace({'MIXTO': 0, 'FEMENINO': 1, 'MASCULINO': 2})
C:\Users\valen\AppData\Local\Temp\ipykernel_121484\4216117425.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datos_filtrados['cole_caracter'] = datos_filtrados['cole_caracter'].replace({'TÉCNICO': 0, 'TÉCNICO/ACADÉMICO': 1, 'ACADÉMICO': 2})
C:\Users\valen\AppData\Local\Temp\ipykernel_121484\4216117425.py:16: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  datos_filtrados['estu_depto_presentacion'] = datos_filtrados['estu_depto_presentacion'].replace({'ANTIOQUIA': 0, 'BOGOTÁ': 1})
C:\Users\valen\AppData\Local\Temp\ipykernel_121484\4216117425.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datos_filtrados['estu_depto_presentacion'] = datos_filtrados['estu_depto_presentacion'].replace({'ANTIOQUIA': 0, 'BOGOTÁ': 1})

In [13]:
datos_filtrados

,periodo,estu_tipodocumento,cole_area_ubicacion,cole_bilingue,cole_calendario,cole_caracter,cole_genero,estu_depto_presentacion,estu_nacionalidad,estu_privado_libertad,...,fami_tienecomputador,fami_tieneinternet,fami_tienelavadora,desemp_ingles,punt_ingles,punt_matematicas,punt_sociales_ciudadanas,punt_c_naturales,punt_lectura_critica,punt_global
0,20224,1,0,0,0,0,0,0,COLOMBIA,N,...,1,1,1,A-,35.0,48.0,46,38,49,222
1,20224,1,0,0,0,1,0,0,COLOMBIA,N,...,1,1,0,A-,40.0,43.0,28,44,44,199
2,20224,1,0,0,0,2,1,0,COLOMBIA,N,...,1,1,1,A2,58.0,48.0,59,47,58,267
4,20224,1,0,0,0,2,0,0,COLOMBIA,N,...,1,1,1,B1,76.0,67.0,75,55,75,343
6,20224,1,0,0,0,2,0,1,COLOMBIA,N,...,1,1,1,A2,61.0,57.0,58,58,60,292
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
635563,20224,1,0,0,0,2,0,1,COLOMBIA,N,...,1,1,1,A1,57.0,62.0,59,58,62,300
635564,20224,0,0,0,0,2,0,0,COLOMBIA,N,...,0,1,1,A1,52.0,44.0,29,41,39,197
635565,20224,1,0,0,0,2,0,1,COLOMBIA,N,...,1,1,1,A-,40.0,51.0,31,39,37,198
635566,20224,1,0,0,0,0,0,0,COLOMBIA,N,...,0,1,1,A-,36.0,45.0,30,37,44,194
635567,20224,1,0,0,0,1,0,0,COLOMBIA,N,...,0,1,0,A2,67.0,77.0,73,66,50,333

In [15]:
ruta_archivo_csv = "C:/Users/valen/OneDrive/Documents/Andes/Octavo/Analitica Computacional/Proyecto3/datos_filtrados.csv"

# Guardar el dataframe en un archivo CSV sin incluir el índice
datos_filtrados.to_csv(ruta_archivo_csv, index=False)